// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.04 Use regions to block out Events and/or the player from\nbeing able to venture into those spots.","parameters":{"Player Restrict":"8","Event Restrict":"9","All Restrict":"10","Player Allow":"11","Event Allow":"12","All Allow":"13"}}
];
