// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"master2015hpZ_myCore","status":true,"description":"install me above all of other master2015hp plugins","parameters":{}},
{"name":"master2015hpZ_meTranslate","status":true,"description":"easiest & cleanest way to localize your game","parameters":{"file name":"MeTranslate","file name 2":"MeLanguages","wait for loading data":"3","language window height offset":"200","import data":"true","export data":"false","translate commands":"true","translate skill desc":"true","special encode list":"[]","autotranslating format":"true","language options":"[\"{\\\"name\\\":\\\"default\\\",\\\"sysImg\\\":\\\"Balloon\\\"}\",\"{\\\"name\\\":\\\"Vietnam\\\",\\\"sysImg\\\":\\\"Weapons3\\\"}\"]"}}
];
